version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: epuser
      POSTGRES_PASSWORD: epsecret
      POSTGRES_DB: epdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/epdb
      SPRING_DATASOURCE_USERNAME: epuser
      SPRING_DATASOURCE_PASSWORD: epsecret
      SERVER_PORT: 3000
    ports:
      - "3000:3000"
    restart: on-failure

volumes:
  pgdata:
